### ISSUE TITLE
shady-dom support

### ISSUE THREAD

**Issue by tylergraf** [jshcrowthe/dialog-el#29]
We're seeing significant performance issues using the shadow dom polyfill when a lot of nodes are rendered in pedigree. So we're moving to using shady-dom.

Would you consider supporting shady-dom in `dialog-el`? It's the only component we're that requires shadow dom. I'm actually not sure all that it entails, but we'll probably fork if it's not supported.

**Comment by jshcrowthe** [comment]
I apologize for the delay on responding to this.

With the Webcomponents JS polyfill in v1 this ultimately is unneeded. The notion of "Shady" and "Shadow" DOM APIs are no different so I will be supporting this by moving to v1.
